print("Nombre del alumno, Areli Jatziri Sandoval Valadez")
print("Lugar de residencia, Rincon de romos, Ags")
print("Fecha de Nacimiento, 24 de Julio de 2002")
print("Color favorito, Rosita pastel")
print("Animal Favorito, Perro")

print("¿Que es programacion?")
print("Es un conjunto de comandos que se le das a una computadora para que realize")
print("¿Porqué es importante la programacion?")
print("Es una parte importante para el avance tecnologico dentro de las industrias")
print("Explica con sus palabras que es herencia.")
print("Es un objeto que tiene todas las caracteristicas de una clase a la que pertecene")
print("Explica con tus palabras que es poliformismo.")
print("Es una operacion que tiene el mismo nombre de diferentes clases.")
print("Explica con tus palabras que es abstracción.")
print("Se refiere a quitar las propiedadesy acciones de un objeto para dehar solo aquellas que sean necesarias")
print("Explica con tus palabras que es encapsulamiento.")
print("Es cuando un objeto trae consigo su funcionalidad y esta se oculta")