#Creditos
#Areli Jatziri Sandoval Valadez

print("Ingenieria en TICS")
A = int(input("Ingresar el semestre: "))

if A == 1: 
	print ("La materias son: ")
	print ("Matematicas discretas 1")
	print ("Calculo Diferencial")
	print ("Fundamentos de programacion")
	print ("Intruduccion a las tics")
	print ("Fundamentos de Investigacion")
	print ("Ingles (Depende de tu nivel)")
	print ("Cretitos del Semestre:26")
elif A == 2:
	print ("Las Materias son:")
	print ("Calculo Integral")
	print ("Programacion orientada objetos")
	print ("Matematicas discretas 2")
	print ("Probabilidad y estadistica")
	print ("Contabilidad y costos")
	print ("Creditos del Semestre:25")
elif A == 3:
	print ("Las materias son")
	print ("Mtematicas aplicadas ")
	print ("Estructura y organizacion de datos")
	print ("Administracion general")
	print ("Fundamentos de Base de datos")
	print ("Elctricidad y magnetismo")
	print ("Algebra lineal")
	print ("Creditos del Semestre:27")
elif A == 4:
	print ("Las materias son:")
	print ("Analisis de señales y sistemas")
	print ("Programacion 2")
	print ("Matematicas para la toma de decisiones")
	print ("Taller de base de datos ")
	print ("Circuitos electricos y electronicos")
	print ("Ingenieria de software")
	print ("Creditos del semestre:28")
elif A == 5: 
	print ("Las materias son:")
	print ("Fundamentos de redes")
	print ("Telecomunicaciones")
	print ("Administracion de proyectos")
	print ("Base de datos distribuidas")
	print ("Arquitectura de computadoras")
	print ("Taller de ingenieria de software")
	print ("Creditos del semestre:28")
elif A == 6:
	print ("Las materias son:")
	print ("Redes de computadoras")
	print ("Programacion web")
	print ("Desarrollo de emprendedores")
	print ("Taller de investigacion")
	print ("Sistemas operativos")
	print ("Tecnologias inalambricas")
	print ("Creditos del semestre:28")
elif A == 7:
	print ("Las materias son:")
	print ("Redes emergentes")
	print ("Desarrollo de aplicasiones para Dips.M")
	print ("Desarrollo sustentable")
	print ("Taller de investigacion 2")
	print ("Sistemas operativos 2")
	print ("Negocios electronicos 1")
	print ("Creditos del semestre:27")
elif A == 8:
	print ("Las materias son:")
	print ("Administracion y seguridad de redes")
	print ("Auditoria en telcnologias de la informacion")
	print ("Interaccion humano computadora")
	print ("Ingenieria del conocimiento")
	print ("Negocios electronicos 2")
	print ("Creditos del semestre:21")
elif A == 9:
	print("Estas en noveno semestre y las actividades a realizar son; ")
	print("Actividades Complementarias")
	print("Especialidad")
	print("Residencias Profesionales")
	print("Servicio Social")
else:
	print ("Error")
print ("FIN")